apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: queue
  namespace: argocd
spec:
  project: shop
  destination: { server: https://kubernetes.default.svc, namespace: shop }
  sources:
    - repoURL: https://stefanprodan.github.io/podinfo
      chart: podinfo
      targetRevision: 6.9.2
      helm:
        valueFiles:
          - $values/environments/dev/values/web-values.yaml
    - repoURL: https://github.com/automatewithcharan/gitops-shop.git
      targetRevision: main
      ref: values
  syncPolicy: { automated: { prune: true, selfHeal: true } }

