apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
spec:
  project: shop
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.4.0
    helm:
      valueFiles:
        - $values/environments/dev/values/redis-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

