apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: shop
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.4.0
    helm:
      valueFiles:
        - $values/environments/dev/values/redis-values.yaml
  - repoURL: https://github.com/automatewithcharan/gitops-shop.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

