apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
spec:
  project: shop
  destination: { server: https://kubernetes.default.svc, namespace: shop }
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: 6.9.2
    helm:
      valueFiles:
        - environments/dev/values/web-values.yaml
      valuesObject:
        serviceMonitor:
          enabled: true
          labels: { release: kube-prom-stack }
  syncPolicy: { automated: { prune: true, selfHeal: true } }
