apiVersion: v1
kind: Service
metadata:
  name: api-podinfo
  namespace: shop
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/instance: api
  ports:
  - name: http
    port: 9898
    targetPort: 9898
  type: ClusterIP
