apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-dev
  namespace: argocd
spec:
  project: shop
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  
  source:
    repoURL: https://github.com/automatewithcharan/gitops-shop.git
    targetRevision: main
    path: environments/dev/apps
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
